packages:
  - "packages/*"
catalog:
  "@antfu/install-pkg": 1.0.0
  "@arethetypeswrong/cli": 0.17.4
  "@changesets/cli": 2.28.1
  "@clack/prompts": 0.10.0
  "@commitlint/cli": 19.8.0
  "@commitlint/config-conventional": 19.8.0
  "@eslint-community/eslint-plugin-eslint-comments": 4.4.1
  "@eslint-react/eslint-plugin": 1.34.1
  "@eslint/compat": 1.2.7
  "@eslint/js": 9.22.0
  "@next/eslint-plugin-next": 15.2.2
  "@size-limit/esbuild-why": 11.2.0
  "@size-limit/preset-small-lib": 11.2.0
  "@stylistic/eslint-plugin": 4.2.0
  "@tanstack/eslint-plugin-query": 5.68.0
  "@total-typescript/ts-reset": 0.6.1
  "@types/eslint-plugin-security": 3.0.0
  "@types/eslint-plugin-tailwindcss": 3.17.0
  "@types/node": 22.13.10
  "@types/react": ^19.0.12
  "@types/react-dom": ^19.0.4
  "@typescript-eslint/parser": ^8.26.1
  "@zayne-labs/toolkit-type-helpers": ^0.8.48
  bumpp: ^10.0.3
  clsx: ^2.1.1
  concurrently: 9.1.2
  cross-env: 7.0.3
  eslint: 9.22.0
  eslint-config-flat-gitignore: 2.1.0
  eslint-flat-config-utils: 2.0.1
  eslint-import-resolver-typescript: 4.1.1
  eslint-merge-processors: ^2.0.0
  eslint-plugin-astro: 1.3.1
  eslint-plugin-import-x: 4.8.0
  eslint-plugin-jsdoc: 50.6.7
  eslint-plugin-jsonc: 2.19.1
  eslint-plugin-n: 17.16.2
  eslint-plugin-perfectionist: 4.10.1
  eslint-plugin-pnpm: ^0.3.1
  eslint-plugin-react-compiler: 19.0.0-beta-e1e972c-20250221
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.19
  eslint-plugin-security: 3.0.1
  eslint-plugin-solid: 0.14.5
  eslint-plugin-svelte: 3.2.1
  eslint-plugin-tailwindcss: 3.18.0
  eslint-plugin-toml: ^0.12.0
  eslint-plugin-unicorn: 57.0.0
  eslint-plugin-vue: 10.0.0
  eslint-plugin-yml: ^1.17.0
  eslint-processor-vue-blocks: 2.0.0
  eslint-typegen: 2.1.0
  globals: 16.0.0
  husky: 9.1.7
  jsonc-eslint-parser: 2.4.0
  lint-staged: 15.5.0
  local-pkg: 1.1.1
  pkg-pr-new: 0.0.41
  prettier: 3.5.3
  publint: 0.3.9
  react: ^19.0.0
  react-dom: ^19.0.0
  size-limit: 11.2.0
  tailwindcss: 3.4.17
  terser: ^5.39.0
  toml-eslint-parser: 0.10.0
  tsup: 8.4.0
  tsx: 4.19.3
  typescript: 5.8.2
  typescript-eslint: 8.26.1
  vitest: 3.0.7
  vue: ^3.5.13
  vue-eslint-parser: 10.1.1
  yaml-eslint-parser: 1.3.0
catalogs:
  conflicts_@arethetypeswrong/cli_h0_17_4:
    "@arethetypeswrong/cli": ^0.17.4
  conflicts_@changesets/cli_h2_28_1:
    "@changesets/cli": ^2.28.1
  conflicts_@size-limit/esbuild-why_h11_2_0:
    "@size-limit/esbuild-why": ^11.2.0
  conflicts_@size-limit/preset-small-lib_h11_2_0:
    "@size-limit/preset-small-lib": ^11.2.0
  conflicts_@total-typescript/ts-reset_h0_6_1:
    "@total-typescript/ts-reset": ^0.6.1
  conflicts_concurrently_h9_1_2:
    concurrently: ^9.1.2
  conflicts_cross-env_h7_0_3:
    cross-env: ^7.0.3
  conflicts_publint_h0_3_7:
    publint: ^0.3.7
  conflicts_size-limit_h11_2_0:
    size-limit: ^11.2.0
  conflicts_tsup_h8_4_0:
    tsup: ^8.4.0
  conflicts_@eslint-react/eslint-plugin_h1_34_1:
    "@eslint-react/eslint-plugin": ^1.34.1
  conflicts_@next/eslint-plugin-next_h15_2_1:
    "@next/eslint-plugin-next": ^15.2.1
  conflicts_@types/node_h22_13_10:
    "@types/node": ^22.13.10
  conflicts_eslint_h9_22_0:
    eslint: ^9.22.0
  conflicts_eslint-plugin-react-hooks_h5_2_0:
    eslint-plugin-react-hooks: ^5.2.0
  conflicts_eslint-plugin-react-refresh_h0_4_19:
    eslint-plugin-react-refresh: ^0.4.19
  conflicts_husky_h9_1_7:
    husky: ^9.1.7
  conflicts_lint-staged_h15_5_0:
    lint-staged: ^15.5.0
  conflicts_prettier_h3_5_3:
    prettier: ^3.5.3
  conflicts_eslint-plugin-solid_h0_14_3:
    eslint-plugin-solid: ^0.14.3
  conflicts_conflicts_@arethetypeswrong/cli_h0_17_4_0_17_4:
    "@arethetypeswrong/cli": 0.17.4
  conflicts_conflicts_@changesets/cli_h2_28_1_2_28_1:
    "@changesets/cli": 2.28.1
  conflicts_conflicts_@size-limit/esbuild-why_h11_2_0_11_2_0:
    "@size-limit/esbuild-why": 11.2.0
  conflicts_conflicts_@size-limit/preset-small-lib_h11_2_0_11_2_0:
    "@size-limit/preset-small-lib": 11.2.0
  conflicts_conflicts_@total-typescript/ts-reset_h0_6_1_0_6_1:
    "@total-typescript/ts-reset": 0.6.1
  conflicts_conflicts_concurrently_h9_1_2_9_1_2:
    concurrently: 9.1.2
  conflicts_conflicts_cross-env_h7_0_3_7_0_3:
    cross-env: 7.0.3
  conflicts_conflicts_publint_h0_3_7_0_3_9:
    publint: 0.3.9
  conflicts_conflicts_size-limit_h11_2_0_11_2_0:
    size-limit: 11.2.0
  conflicts_conflicts_tsup_h8_4_0_8_4_0:
    tsup: 8.4.0
  conflicts_conflicts_@eslint-react/eslint-plugin_h1_34_1_1_34_1:
    "@eslint-react/eslint-plugin": 1.34.1
  conflicts_conflicts_@next/eslint-plugin-next_h15_2_1_15_2_2:
    "@next/eslint-plugin-next": 15.2.2
  conflicts_conflicts_@types/node_h22_13_10_22_13_10:
    "@types/node": 22.13.10
  conflicts_conflicts_eslint_h9_22_0_9_22_0:
    eslint: 9.22.0
  conflicts_conflicts_eslint-plugin-react-hooks_h5_2_0_5_2_0:
    eslint-plugin-react-hooks: 5.2.0
  conflicts_conflicts_eslint-plugin-react-refresh_h0_4_19_0_4_19:
    eslint-plugin-react-refresh: 0.4.19
  conflicts_conflicts_eslint-plugin-solid_h0_14_3_0_14_5:
    eslint-plugin-solid: 0.14.5
  conflicts_conflicts_husky_h9_1_7_9_1_7:
    husky: 9.1.7
  conflicts_conflicts_lint-staged_h15_5_0_15_5_0:
    lint-staged: 15.5.0
  conflicts_conflicts_prettier_h3_5_3_3_5_3:
    prettier: 3.5.3
