packages:
   - packages/*

catalogs:
   eslint:peer:
      "@eslint-react/eslint-plugin": ^4.2.3
      "@next/eslint-plugin-next": ^16.2.4
      "@tanstack/eslint-plugin-query": ^5.100.1
      "@tanstack/eslint-plugin-router": ^1.161.6
      astro-eslint-parser: ^1.4.0
      eslint: ^10.2.1
      eslint-config-expo: ^55.0.0
      eslint-plugin-astro: ^1.7.0
      eslint-plugin-better-tailwindcss: ^4.4.1
      eslint-plugin-depend: ^1.5.0
      eslint-plugin-erasable-syntax-only: ^0.4.0
      eslint-plugin-jsx-a11y: ^6.10.2
      eslint-plugin-react-hooks: ^7.1.1
      eslint-plugin-react-refresh: ^0.5.2
      eslint-plugin-react-you-might-not-need-an-effect: ^0.9.3
      eslint-plugin-solid: ^0.14.5
      eslint-plugin-svelte: ^3.17.1
      eslint-plugin-vue: ^10.9.0
      eslint-plugin-vuejs-accessibility: ^2.5.0
      eslint-processor-vue-blocks: ^2.0.0
      svelte-eslint-parser: ^1.6.0
      vue-eslint-parser: ^10.4.0

   prettier:peer:
      "@ianvs/prettier-plugin-sort-imports": ^4.7.1
      prettier: ^3.8.3
      prettier-plugin-astro: ^0.14.1
      prettier-plugin-classnames: ^0.10.1
      prettier-plugin-merge: ^0.10.1
      prettier-plugin-tailwindcss: ^0.7.2
